### ISSUE TITLE
ERROR: No matching distribution found for pandas==2.0.3

### ISSUE THREAD

**Issue by larkzhang** [coffeeandsecurity/DakshSCRA#3]
Could you please ask ERROR: No matching distribution found for pandas==2.0.3
  The requirement for pandas==2.0.3 is that the version of python used is 3. What is it?

**Comment by coffeeandsecurity** [comment]
Have you tried to install dependencies within the virtual environment? 
Please following these instructions to setup the environment: 
https://github.com/coffeeandsecurity/DakshSCRA/wiki/Tool-Setup

You, must use a virtual environment and then have all the dependencies installed within it. If you still face any issues, do post here.

**Comment by coffeeandsecurity** [comment]
Have you tried to install dependencies within the virtual environment? 
Please following these instructions to setup the environment: 
https://github.com/coffeeandsecurity/DakshSCRA/wiki/Tool-Setup

**Comment by larkzhang** [comment]
This has been solved now because I have some less dependencies, and the missing dependency problem has been solved when I install it separately

**Comment by coffeeandsecurity** [comment]
> This has been solved now because I have some less dependencies, and the missing dependency problem has been solved when I install it separately

Good to know, it got resolved.
