### ISSUE TITLE
At present, it seems that only java, php, JavaScript, python, and mobile are supported, right? Suppose I wrote a rule file in Go language by myself. Can I scan it?

### ISSUE THREAD

**Issue by larkzhang** [coffeeandsecurity/DakshSCRA#5]
At present, it seems that only java, php, JavaScript, python, and mobile are supported, right? Suppose I wrote a rule file in Go language by myself. Can I scan it?

**Comment by coffeeandsecurity** [comment]
This tool is designed to be easily extended by anyone to support any programming languages without requiring changes at the source code level. To extend its rules, you only need to add rules for the programming languages you want it to scan.

- rules/scanning/rulesconfig.xml - Include the path to the rule file
- rules/scanning/platform/[platform-name]/[platform-name].xml - The scanning rule file specific to a platform

I have pushed some Go rules for you to play with. Grab the latest build and feel free to add more rules and extend it.

Usage:
python dakshscra.py -r go -t [target-dir]

Currently, I am busy working on some design changes to make it more versatile. Therefore, adding support for new rules in additional languages has taken a back seat in terms of priority. However, I do aim to include more rules across multiple other platforms as soon as I have completed the top priority changes.

Feel free to extend its rules, and be sure to check back for future updates. If incase you are unable to write certain Go rules but want few specific areas to be included then do propose here and I'll try to find some time to write/update those rules for you.

**Comment by coffeeandsecurity** [comment]
Hope you’ve had a chance to try the Go rules. Let me know if you encountered any issues during scanning. I’ll continue to extend the Go rules as time permits, but if there are specific checks you’d like me to introduce, do let me know.

I’m closing this issue for now. Feel free to reopen it if you have further questions related to this thread or create a new issue ticket if you encounter any other problems.
