### ISSUE TITLE
An issue was found where the contents of the read file were garbled

### ISSUE THREAD

**Issue by larkzhang** [coffeeandsecurity/DakshSCRA#7]
In DakshSCRA/modules/parser.py line 96 with open(filepath, 'r', encoding='ISO-8859-1') as fo_target This piece of code will be garbled when reading data, trying to modify it to utf-8 will be improved, but it is not very absolute, can you specify the encoding format during the runtime, I was going to try to change it by modifying the running parameters, but it didn't work

**Comment by coffeeandsecurity** [comment]
Thanks for raising this! I've added a readfile_FallbackEncoding function (located in /utils/file_utils.py.) that tries multiple encodings (defaulting to ISO-8859-1 and UTF-8) to prevent garbled text. You can customize the encodings by adjusting the fallback_order parameter.

I'll also move this setting to a config file in the future, so you can change it without touching the code. 

Here are the release details - https://github.com/coffeeandsecurity/DakshSCRA/releases/tag/v0.24-beta

For now, I’ll keep this issue open for a few weeks. Let me know how it goes or if you run into any further issues.
